### ISSUE TITLE
It didn't work in RHEL6

### ISSUE THREAD

**Issue by marciodo** [marcopaganini/gnome-cedilla-fix#1]
I tried it in RHEL without success.

**Comment by marcopaganini** [comment]
I don't have RHEL installed here (will do) but for the time being can you provide some details?

- What version of RHEL?
- Did the script fail or just didn't produce accented C's?
- When you type ', followed by c, what happens? Nothing? a c with an accent?
- if you run xterm and type '+c in there, what happens? (need to be xterm, not gnome-terminal)
- Can you paste the contents of /etc/environment?
- Can you paste the result of typing "echo $GTK_XIM_MODULE" (without quotes)
- What version of gnome/window manager/environment are you using

**Comment by marcopaganini** [comment]
No feedback from author in one year. Closing as need more information.
