### ISSUE TITLE
A simpler solution

### ISSUE THREAD

**Issue by adrianoviana87** [marcopaganini/gnome-cedilla-fix#5]
According to [this page](https://askubuntu.com/questions/363115/how-to-type-latin-small-letter-c-with-cedilla)
>
> add one line in `/etc/environment`
>
> `GTK_IM_MODULE=cedilla QT_IM_MODULE=cedilla`

This solution is working on my Pop! OS 20.04.

**Comment by marcopaganini** [comment]
This was one of my first approaches, but I was unable to make it work. Furthermore, for some reason, setting `QT_IM_MODULE=cedilla` breaks some Qt apps like Telegram. If you look at the repo, you'll se that until recently, I used to set these variables in `/etc/environment`, but decided to remove them as they cause the aforementioned problem with Telegram.

**Comment by adrianoviana87** [comment]
Actually, I was wrong. It used to work, but it's not anymore. I'll follow the instructions on this repository. Hopefully, it will work.
